from typing import Any

from tortoise.queryset import QuerySet

from aiosales.models import Product
from aiosales.repositories.abstract import AbstractRepository

class ProductRepository(AbstractRepository[Product]):
    async def add(self, item: Product) -> None: ...
    async def get(self, **reference: Any) -> Product: ...
    async def list(self) -> QuerySet[Product]: ...
    async def filter_with_done_delivery(self) -> QuerySet[Product]: ...